# Stage 1
FROM node:18-alpine as builder
ARG REACT_APP_API_SERVER
ARG REACT_APP_VIDEO_SERVER
RUN echo "REACT_APP_VIDEO_SERVER is set to $REACT_APP_VIDEO_SERVER"

WORKDIR /app
COPY . .
RUN yarn
ENV REACT_APP_API_SERVER=$REACT_APP_API_SERVER
ENV REACT_APP_VIDEO_SERVER=$REACT_APP_VIDEO_SERVER
RUN yarn build
EXPOSE 3000
CMD [ "npx", "serve", "build" ]
